jobs:
  - id: git-daily-commits
    name: 每日 Git 提交汇总（今日）
    schedule: 20 18 * * *
    script: git-daily-commits.js
    args:
      repoPath: /Users/shmily/Documents/win/web-h5
    enabled: true
    webhook: https://open.larksuite.com/open-apis/bot/v2/hook/ca81afcf-5a1a-455d-bdd2-b8862520f8e0
  - id: git-yesterday-commits
    name: test task
    schedule: 52 10 * * *
    script: git-daily-commits.js
    args:
      repoPath: /Users/shmily/Documents/win/web-h5
      extra: yesterday
    enabled: false
    webhook: https://open.larksuite.com/open-apis/bot/v2/hook/ca81afcf-5a1a-455d-bdd2-b8862520f8e0
